modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      method: GET
      preferred_ip_protocol: "ip4"
      follow_redirects: true
      headers:
        User-Agent: ai-trading-blackbox-probe
  http_api_health:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: [200]
      preferred_ip_protocol: "ip4"
      fail_if_body_not_matches_regexp:
        - '"status"\s*:\s*"healthy"'
      headers:
        User-Agent: ai-trading-blackbox-probe
  http_readiness_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: [200]
      preferred_ip_protocol: "ip4"
      fail_if_body_not_matches_regexp:
        - '"status"\s*:\s*"ready"'
      headers:
        User-Agent: ai-trading-blackbox-probe
  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"
  icmp_ping:
    prober: icmp
    timeout: 3s
    icmp:
      preferred_ip_protocol: "ip4"