apiVersion: 1

datasources:
  # Prometheus - System metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    editable: false
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
    secureJsonData: {}
    version: 1

  # QuestDB - Market data and trading metrics
  - name: QuestDB
    type: questdb-questdb-datasource
    access: proxy
    url: http://questdb:9000
    uid: questdb
    editable: false
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: GET
    version: 1

  # Redis - Real-time data and cache metrics
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    uid: redis
    editable: false
    basicAuth: false
    withCredentials: false
    jsonData:
      client: standalone
      poolSize: 5
    version: 1

  # Loki - Log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: false
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: GET
      maxLines: 1000
    version: 1