version: 1
formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(name)s [%(threadName)s] %(message)s"
  structured:
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
