version: 1
default:
  min_sharpe: 1.2        # Minimum Sharpe ratio required for production promotion
  max_drawdown: -0.25    # Maximum acceptable drawdown (negative value)
  min_backtest_trades: 30
  min_win_rate: 0.48
overrides:
  high_frequency_strategy:
    min_sharpe: 1.8
    max_drawdown: -0.30
  conservative_strategy:
    min_sharpe: 0.9
    max_drawdown: -0.20
