groups:
  - name: provider-slo-burn
    interval: 30s
    rules:
      - record: provider:error_ratio_5m
        expr: |
          sum by (provider) (rate(provider_requests_total{status="error"}[5m]))
            /
          clamp_min(sum by (provider) (rate(provider_requests_total{status="success"}[5m])), 1)
      - record: provider:error_ratio_30m
        expr: |
          sum by (provider) (rate(provider_requests_total{status="error"}[30m]))
            /
          clamp_min(sum by (provider) (rate(provider_requests_total{status="success"}[30m])), 1)
      - alert: ProviderFastBurn
        expr: provider:error_ratio_5m > 0.05 and provider:error_ratio_30m > 0.02
        for: 10m
        labels:
          severity: warning
          category: providers
        annotations:
          summary: "Fast SLO burn for provider {{ $labels.provider }}"
          description: |-
            Short window error ratio >5% and medium window >2%. Provider reliability deteriorating; investigate quickly.
      - alert: ProviderSustainedBurn
        expr: provider:error_ratio_30m > 0.03
        for: 30m
        labels:
          severity: critical
          category: providers
        annotations:
          summary: "Sustained SLO burn for provider {{ $labels.provider }}"
          description: |-
            Error ratio >3% over 30m. Consuming error budget; evaluate failover or reduction of dependent workloads.
