groups:
  - name: provider-error-ratio
    interval: 30s
    rules:
      - alert: ProviderHighErrorRatio
        expr: |
          sum by (provider) (rate(provider_requests_total{status="error"}[5m]))
            /
          clamp_min(sum by (provider) (rate(provider_requests_total{status="success"}[5m])), 1)
            > 0.05
        for: 5m
        labels:
          severity: warning
          category: providers
        annotations:
          summary: "High error ratio for provider {{ $labels.provider }}"
          description: |-
            Provider {{ $labels.provider }} has an error ratio >5% over the last 5 minutes.
            Investigate upstream API health, credentials, rate limits, or network issues.
            Dashboard: Grafana -> Provider / Market Data Overview
      - alert: ProviderSevereErrorRatio
        expr: |
          sum by (provider) (rate(provider_requests_total{status="error"}[10m]))
            /
          clamp_min(sum by (provider) (rate(provider_requests_total{status="success"}[10m])), 1)
            > 0.15
        for: 10m
        labels:
          severity: critical
          category: providers
        annotations:
          summary: "Severe error ratio for provider {{ $labels.provider }}"
          description: |-
            Provider {{ $labels.provider }} has an error ratio >15% sustained over 10 minutes.
            Immediate action recommended. Check provider status page, rotate keys, or failover.
