# Prometheus Configuration for Trading System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trading-system'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Infrastructure Services
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'questdb'
    static_configs:
      - targets: ['questdb:9003']  # QuestDB metrics endpoint
    scrape_interval: 30s
    metrics_path: '/metrics'

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Trading Application Services (will be added in later phases)
  - job_name: 'trading-api-gateway'
    static_configs:
      - targets: []  # Will be populated when services are deployed
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'trading-orchestrator'
    static_configs:
      - targets: []
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'trading-risk-engine'
    static_configs:
      - targets: []
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'trading-execution-engine'
    static_configs:
      - targets: []
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'trading-model-server'
    static_configs:
      - targets: []
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'trading-data-ingestion'
    static_configs:
      - targets: []
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'trading-feature-engine'
    static_configs:
      - targets: []
    scrape_interval: 30s
    metrics_path: '/metrics'

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"