# Grafana datasource configuration for AI Trading System
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    uid: prometheus
    
  - name: PostgreSQL
    type: postgres
    url: localhost:5432
    database: trading_db
    user: trading_user
    secureJsonData:
      password: trading_password
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    uid: postgres
    
  - name: Redis
    type: redis-datasource
    url: redis://localhost:6379
    database: "0"
    uid: redis
    
  - name: Loki (Logs)
    type: loki
    access: proxy
    url: http://localhost:3100
    uid: loki