name: Quality Gate

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-ml.txt ]; then pip install -r requirements-ml.txt || true; fi

      - name: Run quality checks
        run: |
          chmod +x scripts/quality_check.sh || true
          ./scripts/quality_check.sh

      - name: Run compose mount validation
        run: |
          chmod +x scripts/validate_compose_mounts.sh || true
          ./scripts/validate_compose_mounts.sh

      - name: Generate SBOM (optional)
        if: always()
        run: |
          if [ -x scripts/generate_sbom.sh ]; then ./scripts/generate_sbom.sh || echo "SBOM generation non-fatal"; fi

      - name: Archive quality artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-logs
          path: |
            logs/**
            *.sbom.json
          if-no-files-found: ignore
