name: Shell Script Lint

on:
  push:
    paths:
      - 'scripts/**/*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'scripts/**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: |
          echo 'Running shellcheck...'
          find scripts -type f -name '*.sh' -print0 | xargs -0 -n1 shellcheck --severity=style
