# Production AI Models Configuration
# Last updated: 2025-09-04

# Default model settings
default_settings:
  temperature: 0.7
  max_tokens: 2000
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout: 30
  retry_attempts: 3

# Available models for production
models:
  # Analysis models
  analysis:
    primary: qwen2.5:72b
    fallback: mixtral:8x22b
    specialized:
      technical: deepseek-v3:latest
      fundamental: yi:34b
      sentiment: command-r-plus:104b
  
  # Trading models  
  trading:
    primary: mixtral:8x22b
    fallback: qwen2.5:72b
    specialized:
      risk: solar:10.7b
      execution: phi3:14b
      strategy: deepseek-v3:latest
  
  # Research models
  research:
    primary: command-r-plus:104b
    fallback: yi:34b
    specialized:
      market: qwen2.5:72b
      news: solar:10.7b
      reports: mixtral:8x22b

# Model-specific overrides
model_overrides:
  qwen2.5:72b:
    temperature: 0.6
    max_tokens: 8000  # Increased for 72B model
  
  mixtral:8x22b:
    temperature: 0.7
    max_tokens: 6000  # Increased for 8x22b model
    
  deepseek-v3:latest:
    temperature: 0.5
    max_tokens: 8000  # Very large context for V3
    
  yi:34b:
    temperature: 0.8
    max_tokens: 4000  # Increased for 34B model
    
  command-r-plus:104b:
    temperature: 0.7
    max_tokens: 128000  # Command-R-Plus supports 128k context
    
  solar:10.7b:
    temperature: 0.6
    max_tokens: 2000
    
  phi3:14b:
    temperature: 0.5
    max_tokens: 2048  # Increased for 14B model

# Model routing rules
routing_rules:
  # Route by task type
  task_routing:
    market_analysis: [qwen2.5:72b, mixtral:8x22b, deepseek-v3:latest]
    risk_assessment: [solar:10.7b, deepseek-v3:latest, phi3:14b]
    trade_execution: [phi3:14b, mixtral:8x22b, qwen2.5:72b]
    strategy_optimization: [deepseek-v3:latest, qwen2.5:72b, yi:34b]
    sentiment_analysis: [command-r-plus:104b, solar:10.7b, yi:34b]
    report_generation: [mixtral:8x22b, command-r-plus:104b, qwen2.5:72b]
  
  # Load balancing weights (higher = more traffic)
  load_weights:
    qwen2.5:72b: 25
    mixtral:8x22b: 20
    deepseek-v3:latest: 15
    yi:34b: 10
    command-r-plus:104b: 15
    solar:10.7b: 10
    phi3:14b: 5

# Performance thresholds
performance_thresholds:
  max_latency_ms: 5000
  min_accuracy: 0.85
  max_error_rate: 0.05
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60

# Resource limits
resource_limits:
  max_concurrent_requests: 50
  max_requests_per_minute: 500
  max_tokens_per_minute: 100000
  cache_ttl_seconds: 300